image: maven:3.8.1-openjdk-16

cache:
  paths:
    - .m2/

stages:
  - build
  - deploy

maven-build:
  stage: build
  script: "mvn clean package -DskipTests"

deploy:
  stage: deploy
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$APP_NAME --api-key=$HEROKU_API_KEY
  only:
    - master